import streamlit as st
import requests
import datetime

from utils.chat_history import init_session, create_new_chat, add_message, get_messages

BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat system
init_session()

# ==========================
# SIDEBAR (Chat History)
# ==========================
st.sidebar.title("💬 Chats")

# Add unique key for New Chat button
if st.sidebar.button("➕ New Chat", key="new_chat_button"):
    create_new_chat()

# Use unique keys for each chat button
for chat_id, chat_data in st.session_state.chats.items():
    title = chat_data["title"]
    
    # Create a unique key for each button using chat_id
    button_key = f"chat_button_{chat_id}"
    
    if st.sidebar.button(title, key=button_key):
        st.session_state.current_chat = chat_id

# ==========================
# DISPLAY CHAT
# ==========================

messages = get_messages()

for msg in messages:
    if msg["role"] == "user":
        st.chat_message("user").write(msg["content"])
    else:
        st.chat_message("assistant").write(msg["content"])

# ==========================
# CHAT INPUT
# ==========================

user_input = st.chat_input("Plan a trip to Islamabad for 5 days...")

if user_input:

    add_message("user", user_input)

    st.chat_message("user").write(user_input)

    try:
        with st.spinner("Bot is thinking..."):
            payload = {
            "question": user_input,
            "thread_id": st.session_state.current_chat
            }

            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:

            answer = response.json().get("answer", "No answer returned.")

            markdown_content = f"""
# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Syed Mir Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify information before travel.*
"""

            add_message("assistant", markdown_content)

            st.chat_message("assistant").markdown(markdown_content)

        else:
            st.error("Bot failed to respond: " + response.text)

    except Exception as e:
        st.error(f"Response failed due to {e}")
